
const translations = {
    
    afktemx: 'යාලුවනේ, ඔබට සම්පූර්ණ ගිවිසුමක් තැබීමට අවශ්‍යද, නැතහොත් කුමක් ද?',
    afkdone: 'AFK කට්ටලය,
    afkdel: 'ආපසු සාදරයෙන් පිළිගනිමු',
    afktime: 'එතැන් සිට ඈත',
    with: 'හේතුව',
    afkmsg: 'ඔබ ගැන සඳහන් කරන ඕනෑම කෙනෙකුට මම දැනුම් දෙන්නම්',
    afktag: 'පරිශීලකයා AFK',
    name: 'නම',
    noMention: 'පරිශීලකයෙකු සඳහන් කරන්න',
    userDb: 'පරිශීලකයා මගේ දත්ත ගබඩාවේ නැත',
    example: 'උදාහරණය',
    
    //-- Stick reaction
    killmsg: 'මිය ගියේය',
    kismsg: 'ට හාදුවක් දුන්නා ',
    patmsg: 'පැට්',
    slapmsg: 'කම්මුල් පහරක්',

    next: 'ඊළඟ',
    hi: 'හෙලෝ',
    gp: 'සමූහය',
    nobbot: 'මෙම විධානය භාවිතා කළ හැක්කේ ප්‍රධාන බොට් එකේ පමණි',
    botqr: '* බොට් එකක් වීමට මෙම කේතය භාවිතා කරන්න *\n\n1. ඉහළ දකුණු කෙළවරේ ඇති තිත් තුන මත ක්ලික් කරන්න.\n2. සම්බන්ධිත උපාංග තට්ටු කරන්න.\n3. දුරකථන අංකය සමඟ *සබැඳිය තෝරන්න*\n\n*සටහන:* කේතය වලංගු වන්නේ මෙම අංකය සඳහා පමණි.',
    recon: 'සම්බන්ධතාවය නැති විය ...',
    sesClose: 'සම්බන්ධතාවය වසා ඇත, ඔබට *ID* යැවීමෙන් අතින් සම්බන්ධ විය යුතුය',
    connet: 'සාර්ථකව සම්බන්ධ කර ඇත',
    connID: '*සාර්ථකව සම්බන්ධයි!*\n\nතත්පර කිහිපයකින්, ඔබ නැවත සම්බන්ධ වීමට භාවිතා කළ යුතු *id* අපි ඔබට එවන්නෙමු\n\n* සටහන: * කණ්ඩායමෙන් ඉවත් වන්න *✦ᴀꜱᴜᴋᴀ ᴋɪɴɢ✦ ┃ ᴅᴀʀᴋ ꜱʜᴀᴅᴏᴡ*\nමෙම සබැඳිය සුරකින්න එවිට ඔබට පසුව සම්බන්ධ විය හැක\nhttps://whatsapp.com/channel/0029Vb9cu0FIiRoxxrIMee3J',
    connMsg: 'ඊළඟ වතාවේ ඔබ සම්බන්ධ වන විට, තවත් *QR* කේතයක් ස්කෑන් නොකර ලොග් වීමට පහත පණිවිඩය යවන්න',
    botlist: 'ක්රියාකාරී උප බොට් ලැයිස්තුව',
    newcode: (usedPrefix) => `නියමයි! ඔබට දැන් භාවිතා කළ හැකිය *${usedPrefix}බොට්ක්ලෝන්* නව QR කේතයක් ඉල්ලීමට`,
    nsbot: 'මෙම විධානය *සක්‍රීය උප බොට් සඳහා පමණි* ',
    msgcode: 'නව කේතය ඔබගේ පුද්ගලික කතාබස් වෙත යවා ඇත',
    stopbot: 'බොට් විසන්ධි විය',

    total: 'සම්පූර්ණ',
    tx: 'සම්පේෂණය',
    txdone: 'සම්පේෂණය එකතු කරා',
    cmdlist: '*විධාන ලැයිස්තුව*\n\n▢ *තොරතුරු:* එය *තද* නම්, එය අවහිර කර ඇත',
    notext: 'පෙළ එකතු කිරීමෙන් නැවත නැවත කරන්න',
    textSe: 'Separate the text with a',
    reply: 'පණිවිඩයකට පිළිතුරු දෙන්න',
    replyImg: 'රූපයකට පිළිතුරු දෙන්න',
    cmdSave: 'විධානය සුරැකින ලදී',

    oversizePrem: 'ගොනු ප්‍රමාණය බාගත කිරීමේ සීමාව ඉක්මවයි',
    error: 'දෝෂයක් ඇති විය, කරුණාකර පසුව නැවත උත්සාහ කරන්න ',
    size: 'ප්‍රමාණය',
    link: 'සැබැදිය',
    dev: 'සංවර්ධක',
    version: 'පිටපත',
    searchTo: (value, usedPrefix, command) => `හි සෙවීමට ${value}:\n\n📌භාවිතය: *${usedPrefix + command} <text>*\n\nබාගත කිරීමට URL වෙතින්:\n*${usedPrefix + command}* <link>`,
    search: (value) => `ඔබට සෙවිය යුතු දේ *${value}* හි ඇතුළත් කරන්න`,
    lastUp: 'අවසාන යාවත්කාලීන කිරීම',
    noLink: (value) => `Enter a ${value} link`,
    title: 'Title',
    noUsername: 'Enter a Username',
    username: 'Username',
    followers: 'Followers',
    follows: 'Following',
    bio: 'Bio',
    posts: 'Posts',
    aploud: 'Uploaded',
    limitdl: 'The file exceeds the download limit',
    limitdlTe: 'Upgrade to premium to download files up to',
    duration: 'Duration',
    views: 'Views',
    quality: 'Quality',
    type: 'Type',
    desc: 'Description',
    useCmd: 'Command usage',
    noNum: 'Enter only numbers',
    random: 'Random',

    purse: 'Purse',
    dmd: 'Diamonds',
    money: 'Coins',
    bank: 'Bank',
    itemV: 'To view all *Items*',
    isNan: 'The amount must be a valid number',
    voucher: 'Voucher',
    buy: 'Purchased',
    buyCount: 'Quantity purchased',
    spent: 'Spent',
    buyNan: (value) => `You don't have enough *${value}* to buy`,
    noItem: (usedPrefix) => `That item doesn't exist:\n\n*${usedPrefix}shop* to see available items`,
    noTime: 'Invalid time format',
    second: 'Second(s)',
    hour: 'Hour(s)',
    minute: 'Minute(s)',
    day: 'Day(s)',

    robCd: 'You cannot commit a *Crime* at this time. You must wait',
    crime: 'You have successfully committed a crime',
    crimeAl: 'You were not very careful when entering to steal and activated the alarm. You could only take',
    robMul: 'Oh no! Your crime has failed and you have been fined',
    victin: 'Victim',
    robDo: 'You stole',
    tag: 'Tag',
    dailyCd: 'You have already collected your daily reward. Come back in',
    daily: 'Daily Reward',
    amount: 'Amount',
    dep: (value) => `You have deposited *${value}🪙* to the Bank`,
    depNan: 'You have no money to deposit',
    resBt: 'නැවතත්',
    lbTitle: 'නායක මණ්ඩලය',
    top: 'Top',
    lvl: 'ස්ථානය',
    of: 'පිළිබඳ',
    you: 'ඔබ',
    rank: 'තරාතිරම',
    fxp: 'Xp මට්ටම ඉහළ නැංවීමට අවශ්‍යයි ',
    lvlbfor: 'පෙර මට්ටම',
    lvlup: 'දැනට පවතින මට්ටමට',
    mineCd: 'ඔබට පතල වෙත ආපසු යා හැක',
    mine: 'නියමයි! ඔබ කැණීම් කළා',
    restEcon: 'බොට් ආර්ථිකය යථා තත්ත්වයට පත් කර ඇත',
    shop: 'සාප්පු යන්න',
    shopMsg: 'ඔබට භාවිතයෙන් මිලදී ගත හැකිය',
    prem: 'වාරික',
    onTransfer: 'ඔබ මාරු කිරීමක් කරනවා',
    transItem: 'මාරු කළ හැකි අයිතම',
    confirm: 'ඔබට මාරු කිරීමට අවශ්‍ය බව විශ්වාසද',
    to: 'ට',
    payNan: 'මාරු කිරීමට ප්‍රමාණවත් අරමුදල් නොමැත',
    payCd: 'කාලය අවසන් වී ඇත',
    cancelPay: 'මාරු කිරීම අවලංගුයි',
    pay: 'මාරු කිරීම',
    payError: 'මාරු කිරීමේ දෝෂයකි',
    wd: 'ඔබ ඉවත් වීමට උත්සාහ කරන්නේ *කාසි* කීයක් ද? ',
    wdYes: 'ඔබ ඉවත් වී ඇත',
    noWd: 'ඔබට බැංකුවේ ඇති ප්‍රමාණයට වඩා වැඩි මුදලක් ඔබට ආපසු ගත නොහැක',
    weeklyCd: `එය සතිපතා ත්‍යාගයක් ලෙස හැඳින්වේ 😉. ආපසු එන්න`,
    weekly: '*සතිපතා ත්‍යාගය* \n\noh! දැනටමත් සතියක් ගත වී තිබේද? කෙසේ වෙතත්, මෙන්න',
    workCd: 'ඔබට නැවත වැඩට යා හැක',

    nable: 'සක්රිය කර ඇත',
    disable: 'අක්‍රිය කර ඇත',
    toBot: 'මෙම බොට් සඳහා',
    toGp: 'මෙම සමූහය සඳහා',
    gaytex: 'මෙම සමලිංගිකයා උල්ලංඝනය කිරීමට කැමති කාටද?',
    result: 'ප්‍රතිඵල',
    shipCd: 'ඔබට ඇතුළත වෙනත් හවුල්කරුවෙකු තෝරා ගත හැකිය',
    shipp: 'දවසේ යුවල',
    toaud: 'ඔබට විධානය සමඟ mp3 බවට පරිවර්තනය කිරීමට අවශ්‍ය වීඩියෝව හෝ හඬ සටහනට පිළිතුරු දෙන්න',
    toav: 'ඔබට හඬ සටහනකට පරිවර්තනය කිරීමට අවශ්‍ය ශ්‍රව්‍යයට පිළිතුරු දෙන්න',

    noGame: 'ක්‍රීඩාවක නොවේ',
    resGame: '*Tictactoe* සැසිය නැවත සකස් කර ඇත',
    gameOff: 'ක්රීඩාව අවසන් වී ඇත',
    gaDone: 'නිවැරදි පිළිතුර',
    win: 'ඔබ දිනුම්',
    mathOff: 'තවත් අවස්ථා නැත',
    chance: 'අවස්ථාව',
    answer: 'පිළිතුර',
    mathError: '*වැරදි පිළිතුර* \n \n තවමත් ඇත',
    gameMode: 'මෙම කණ්ඩායම තුළ තවමත් පිළිතුරු නොමැති ප්‍රශ්න තිබේ',
    time: 'කාලය',
    timeOff: 'කාලය අවසන්! \n පිළිතුර වන්නේ:',
    reward: "ත්‍යාගය',
    pptCd: 'නැවත සෙල්ලම් කිරීමට, ඔබ බලා සිටිය යුතුය ',
    ppt: (usedPrefix, command) => `Select rock/paper/scissors\n\n📌 උදාහරණය: *${usedPrefix + command}* පත්‍රය`,
    coinNan: 'ඔබට සෙල්ලම් කිරීමට\' ප්‍රමාණවත්* කාසි* නොමැත',
    stone: 'පාෂාණ',
    sciss: 'කතුරු',
    paper: 'කොළය',
    tie: 'අඳින්න',
    win: 'ඔබ දිනුම්',
    lost: 'ඔබ පැරදියි',
    roulet: (usedPrefix) => `ඔබට රූලට් ක්‍රීඩාවක ඔට්ටු කිහිපයක් තැබිය හැකිය.\n\nUsage: *${usedPrefix}roulette* <amount> <space>\n\nගෙවීම් ගුණකය`,
    rouletCd: 'ඔබ දැනටමත් ඔට්ටුවක් තබා ඇත. කරුණාකර රැඳී සිටින්න',
    moreInfo: 'වැඩි විස්තර සඳහා',
    betMin: 'ඔට්ටු මුදලට වඩා වැඩි විය යුතුය',
    betMax: 'ඔට්ටු මුදල උපරිම සීමාව ඉක්මවයි',
    betNan: 'ඔබට එම ඔට්ටුව තැබීමට ප්‍රමාණවත් *කාසි* නොමැත '',
    in: 'තුළ',
    bet: 'ඔබ ඔට්ටුවක් තබා ඇත',
    fell: 'රූලට් එක ගොඩ බැස්සේය',
    slotC: 'ඔබ එය පාහේ සාදා ඇත, දිගටම උත්සාහ කරන්න :)',

    delWarnUser: 'An admin reduced your warning, you now have',
    warnNan: 'The user has no warnings',
    delwarn: 'Unwarn',
    warns: 'Warnings',
    warn: 'Warning',
    warnRec: 'You received a warning from an admin',
    numError: 'Incorrect number',
    promote: 'User Promoted',
    demote: 'User Demoted',
    gpInfo: 'Group Info',
    members: 'Members',
    gpOwner: 'Group Owner',
    admin: 'Admin',
    gpConf: 'Group Configuration',
    gpConfMsg: 'Message Configuration',
    kick: 'User Kicked',
    linkGp: 'Group Link',
    preNan: 'Enter a valid prefix number',
    gpNanPre: 'The group has no members with the prefix',
    userPref: 'Users with the prefix',
    profile: 'Profile',
    number: 'Number',
    age: 'Age',
    gender: 'Gender',
    lang: 'Language',
    regOn: 'Registered',
    xpUp: 'Ready to',
    upNan: 'Remaining to level up',
    gpRulesNan: 'Group has no rules at the moment',
    gpRules: 'Group Rules',
    rulesMsgOn: 'Group *Rules* have been set',
    rulesMsg: 'Enter the Group Rules',
    welMsgOn: 'Welcome message has been set',
    leaMsgOn: 'Goodbye message has been set',
    welMsg: 'Enter the Welcome message\n\n@user (mention)\n@group (Group name)\n@desc (Group description)',
    leaMsg: 'Enter the Goodbye message\n\n@user (mention)',
    gpSetting: 'Group Settings\n\nOpen and close the group',
    user: 'User',
    userWarn: 'User Warned',
    wningUser: (war) => `If you receive *${war}* warnings, you will be automatically removed from the group`,
    warnMaxU: (war) => `The user exceeded *${war}* warnings and will be removed`,
    blockNan: 'No Blocked Numbers',
    bckList: 'Blocked List',
    donate: '*DONATION*\nYou can donate if you want to help keep the bot active',
    langList: 'Select the language you want to use\n\n≡ *Available Languages*',
    expire: 'Expires in',
    ping: 'Speed',
    uptime: 'Uptime',
    gpNsfw: (usedPrefix) => `The group does not allow NSFW content\nUse this group\n${bgp3}\n\nIf you are an admin, enable it with\n*${usedPrefix}enable* nsfw`,
    nsfwAge: 'You are under age! Come back when you\'re over 18',
    addPremUser: 'You are now a Premium User',
    banChat: 'Bot has been disabled in this group',
    unBanChat: 'Bot is active in this group',
    banUser: 'You can no longer use my commands',
    unBanUser: 'You have been unbanned',
    restartBot: 'Restarting Bot...\nPlease wait',

    genderList: 'Available Genders',
    man: 'Male',
    woman: 'Female',
    other: 'Other',
    regIsOn: 'You are already registered\n\nDo you want to register again?\n\n 📌 Use this command to remove your registration',
    nameMax: 'The name is too long',
    oldReg: 'වාව්, සීයාට බොට් සමඟ සෙල්ලම් කිරීමට අවශ්‍යයි',
    numSn: 'අනුක්‍රමික අංකය ',
    snVerify: 'විධානය සමඟ ඔබේ අනුක්‍රමික අංකය තහවුරු කරන්න,
    snError: 'වැරදි අනුක්‍රමික අංකය',
    unReg: 'ලියාපදිංචි කිරීම අවලංගු කරා',
    stickError: 'පරිවර්තනය අසාර්ථක විය, පළමුව *රූපය / වීඩියෝ / gif* යැවීමට උත්සාහ කර පසුව විධානය සමඟ පිළිතුරු දෙන්න',
    tgStick: 'ටෙලිග්‍රාම් ස්ටිකර් ඇසුරුමකට සබැඳියක් ඇතුළු කරන්න',
    replyStick: 'ස්ටිකරයකට පිළිතුරු දෙන්න',
    ssWeb: 'වෙබ් පිටුවක URL එක ඇතුලත් කරන්න',
    tradList: 'සහාය දක්වන භාෂා ලැයිස්තුව',
    searchError: 'ප්‍රතිඵල කිසිවක් හමු නොවීය',

    rownerH: 'මෙම විධානය භාවිතා කළ හැක්කේ *Bot Creator*හට පමණි',
    ownerH: 'මෙම විධානය භාවිතා කළ හැක්කේ *හිමිකරු සහ උප බොට්ස්*',
    modsH: 'මෙම කාර්යය *Bot Moderators* සඳහා පමණි',
    premH: 'මෙම විධානය *වාරික සාමාජිකයින් සඳහා පමණි*\n\nවැඩිදුර තොරතුරු සඳහා */වාරික* ටයිප් කරන්න',
    groupH: 'මෙම විධානය භාවිතා කළ හැක්කේ කණ්ඩායම් වශයෙන් පමණි',
    privateH: 'මෙම විධානය භාවිතා කළ හැක්කේ *Bot\'s private chat* තුළ පමණි.',
    adminH: 'මෙම විධානය *සමූහ පරිපාලකයින් සඳහා පමණි*',
    botAdmin: 'මෙම විධානය භාවිතා කිරීමට, මම *පරිපාලක* විය යුතුය!',
    unregH: 'ටයිප් කිරීමෙන් මෙම විශේෂාංගය භාවිතා කිරීමට ලියාපදිංචි වන්න:\n\n*/reg*',
    ig: `▢ Instagram හි මාව අනුගමනය කරන්න\n${igfg}`
}

export default translations
